language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "OuxW8QJr84SfTXOfonvvuHWvAqQOMmHmfSkVvu1Ys7qmg7pfYg8e41itC7tMd9QuXHoHKtBM1oyLPJClwXqyt0GwnNspPOWMyDpX0yc5A9oyVpVgbifn/lacTOS3hs9UFvd/ankheZYcwiZoTz0KOTgVafyw0i1SvE3Nww8cwYU="
    - secure: "MNWvsP1nGlm3VcB9MWeFa9YJjLTmkvUcuVqpfs6/zuYIKoS6kXgfzurx+veFjbwnGy0R8/Rp9Eg83LBdcuJyFmZ0Pon8JeOy1yc8knhBQXNIR0mMk5ETj9BpNfRH5ry87nkPpAonDnuPH9N0IF0mYpcC+SjK49DttqyXztfzmEg="

install:
   - npm install -g grunt-cli
   - npm -g install bower
   - npm install
   - bower install

script:
   - grunt test:remote
